Table Usuario {
    id serial [pk]
    rol varchar(13) [not null] 
    nombre varchar(100) [not null]
    direccion varchar(200)
    telefono varchar(15)
    email varchar(100)
    fecha_registro date
}

Table Cuenta {
    id serial [pk]
    usuario int [not null] // FK 
    tipo varchar(50)
    saldo decimal(17,2)
    fecha_apertura date
    estado varchar(20)
}

Table Transaccion {
    id serial [pk, not null]
    cuenta int [not null] // FK
    tipo varchar(30)
    monto decimal(12,2)
    fecha_hora timestamp
    descripcion text
}

Table Prestamo {
    id serial [pk]
    usuario int [not null] // FK
    monto decimal(15,2)
    tasa_interes decimal(5,2)
    fecha_inicio date
    fecha_fin date
    estado varchar(20)
}

Table PagoPrestamo {
    id serial [pk]
    prestamo int [not null] // FK
    monto_pagado decimal(12,2)
    fecha_pago date
    metodo_pago varchar(50)
}

Ref: Usuario.id < Cuenta.usuario
Ref: Cuenta.id < Transaccion.cuenta
Ref: Usuario.id < Prestamo.usuario
Ref: Prestamo.id < PagoPrestamo.prestamo